### ISSUE TITLE
BUG-1: Code block outside of container on mobile

### ISSUE THREAD

**Issue by bit172** [r-saba/blog#1]
**Describe The Bug**

The block of code on the async-await blog post is outside of the blog post container.

**To Reproduce**

1. Go to `https://www.ragith.com/blog/async-await` on mobile.
2. See the block of code going outside of the container.

**Expected Behavior**
The block of code should be part of the blog's readable space.

**Screenshots**

![Screenshot_20210221-210249](https://user-images.githubusercontent.com/36024638/108648069-495ae500-7488-11eb-8130-3ccb10af8a8c.png)

**Smartphone (please complete the following information):**

 - Device: Pixel 4
 - OS: Android 11
 - Browser: Chrome 88.0.4324.181

**Comment by r-saba** [comment]
> **Describe The Bug**
> 
> The block of code on the async-await blog post is outside of the blog post container.
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Go to `https://www.ragith.com/blog/async-await` on mobile.
> 2. See the block of code going outside of the container.
> 
> **Expected Behavior**
> The block of code should be part of the blog's readable space.
> 
> **Screenshots**
> 
> ![Screenshot_20210221-210249](https://user-images.githubusercontent.com/36024638/108648069-495ae500-7488-11eb-8130-3ccb10af8a8c.png)
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Pixel 4
> * OS: Android 11
> * Browser: Chrome 88.0.4324.181

Thank you for bringing this to my attention. I will promptly resolve this issue, if you feel like resolving it yourself feel free to make PR

**Comment by r-saba** [comment]
Thanks @bit172. I'm now using `Prismjs` to style markdown in this app. Text has horizontal scrolling and is highlighted.

![image](https://user-images.githubusercontent.com/25574985/110282783-1434b380-7fad-11eb-9750-c3b1d5af342d.png)

**Comment by bit172** [comment]
![image](https://user-images.githubusercontent.com/36024638/110356516-59d29a00-8008-11eb-964e-e544bfd9173a.png)
